### ISSUE TITLE
Add support for latest version of swift

### ISSUE THREAD

**Issue by sweetysmilez14** [Afur/flutter_html_to_pdf#10]
I am hitting this error

The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

Kindly add support for latest version of swift. Thank you

**Comment by Afur** [comment]
Hi, just add empty Swift class to your iOS project, it will automatically add SWIFT_VERSION to your configuration. Plugin already have provided SWIFT_VERSION.

**Comment by UjjwaRaijada** [comment]
> Hi, just add empty Swift class to your iOS project, it will automatically add SWIFT_VERSION to your configuration. Plugin already have provided SWIFT_VERSION.

How can we add SWIFT class. Please help. Thanks
