### ISSUE TITLE
IOS Version

### ISSUE THREAD

**Issue by pboethig** [Afur/flutter_html_to_pdf#20]
`flutter_html_to_pdf` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by pboethig** [comment]
Whats the problem here. Please help

**Comment by Afur** [comment]
Hi, checkout this [this](https://github.com/Afur/flutter_html_to_pdf/issues/10)
