### ISSUE TITLE
Flutter 2.0: Support Sound Null Safety

### ISSUE THREAD

**Issue by leecommamichael** [Afur/flutter_html_to_pdf#41]
Now that Flutter 2.0 is out, teams like mine are looking to use sound null-safety.
**However,** the Dart Team's guidance is to wait for dependencies to support sound null-safety before our app opts-in.

**Comment by Afur** [comment]
Hello @leecommamichael I'll try to migrate this library as soon as possible but honestly I don't have much time right now to constantly support this library. If you really need this ASAP feel free to contribute.
