### ISSUE TITLE
margin on the right side of the page

### ISSUE THREAD

**Issue by sh3rlock97** [Afur/flutter_html_to_pdf#49]
![image](https://user-images.githubusercontent.com/36266749/126892193-b4cf373f-131e-4502-a8b9-eb927564fa9d.png)

As you can see, there is a margin on the right side, which is really bad when using a background-color on html or body. Is it possible to remove this margin?

**Comment by Afur** [comment]
Hello ✋ 
Unfortunately I am currently too busy to work on the development of this library. Any kind of contribution will be welcomed and published. 🙏
