### ISSUE TITLE
Feature request: Generate pdf dynamically

### ISSUE THREAD

**Issue by Rickem** [Afur/flutter_html_to_pdf#5]
Is there a wait to pass some variables to the html templates?

**Comment by Afur** [comment]
Hi, could you provide more details about your feature request?

**Comment by Rickem** [comment]
Hi, I was wondering if one could use the plugin to genarate an invoice. That means having and html template containing placeholders which will be replaced with some values from a form. 
I assume that the template would be similar to handlebars (just an exemple).

**Comment by joeblew99** [comment]
There are quite a few html template packages out there i think. 

steps:
1. take some JSON and use it as the data source and bind with the HTML Template.
2.  bind the two together, save as HTML and gen the PDF.

**Comment by Afur** [comment]
@Rickem Yes, with this plugin you can generate an invoice very easily. For example, you can create HTML template and fill it with your values by using string interpolation.

**Comment by Rickem** [comment]
Thanks guys. I'll try it out and get back to you.
