### ISSUE TITLE
Pluggin use deprecated version of Android embedding

### ISSUE THREAD

**Issue by Mvhd** [Afur/flutter_html_to_pdf#52]
![16313061361862394791925036958846](https://user-images.githubusercontent.com/39708245/132914721-757346d8-35d4-4709-a1a4-e8a6ece881e6.jpg)
Kindly assist update this plugging to the current Android V2 embedding. I am enjoying your plugging it'll hurt me if Flutter removes it

**Comment by ystekno** [comment]
I get the same error in "flutter 2.2.3" and "flutter 2.5" ...Is there anyone who can help us?

![pdf_error](https://user-images.githubusercontent.com/51874093/133226757-62524101-2b7d-4bf8-a4bb-a3be8d9d39f1.jpg)

**Comment by niypoo** [comment]
I'm facing same warning !

**Comment by Afur** [comment]
Could you create PR with the fix?

**Comment by Mvhd** [comment]
> Could you create PR with  the package developer should update something to the V2 Android embedding.

> I'm facing same warning !

Only the package developer can update it to the V2 Android embedding.
