### ISSUE TITLE
Printing the PDF

### ISSUE THREAD

**Issue by joeblew99** [Afur/flutter_html_to_pdf#6]
i think we could use this.
https://github.com/DavBfr/dart_pdf/tree/master/printing
It is NOT driven from HTML, but i think i make it work.

Is this something others want too ?

**Comment by Afur** [comment]
My main idea when I started working **html_to_pdf** plugin was to bring the ease of creating dynamic documents into Flutter. I was trying to use **dart_pdf** plugin but for the tables it requires more complicated code than HTML.

**Comment by premy** [comment]
@joeblew99 where you able to print using the printing library you mentioned. If so would you care to show how you implemented it?

**Comment by joeblew99** [comment]
@premy i never got time to try.

Instead i decided to use the PDF to Printing Plugin. You have to write builders for each widget to output as PDF. 
I used HTML to Flutter Widgets so i can drive the system from just HTML.

**Comment by premy** [comment]
@joeblew99 thanks for your answer mate. Do you mean these packages:
dart pdf: https://pub.dartlang.org/packages/pdf
flutter printing: https://pub.dartlang.org/packages/printing
???
I checked them out but didn't find an example on how to "to write builders for each widget to output as PDF." Could you maybe share some code?

**Comment by joeblew99** [comment]
@premy 

Look here: https://github.com/DavBfr/dart_pdf/blob/master/pdf/example/main.dart#L9

As you can see they are outputting PDF for a Page, but there is no reason you cant do that at a Widget level too right.
So then all you really want to to do is when you make a Flutter widget add add a BuildPDF() function also.

**Comment by Afur** [comment]
@joeblew99 Okay, in previous comment I was talking about the much earlier concept of this plugin when you had to set (x,y) coordinates to draw elements on the PDF page. Now this rendering looks much easier and it's looks like good alternative to HTML rendering.

**Comment by joeblew99** [comment]
@Afur actually i think your HTML to PDF is the right way to go these days.

I use HTML to describe all Flutter page and widgets. These are just converted at runtime to flutter widgets.
SO for the PDF i can use the same HTML and then convert to PDF.
SO i get a nice clean architecture.

For doing html to PDF everyone uses the wkhtmltopdf lib.
For golang wrapper you can use this: https://github.com/SebastiaanKlippert/go-wkhtmltopdf
SO i just do the PDF output Server side and return it to the Flutter client. 
The HTML came from the HTML on the server anyway.
This might seem like cheating but i just got sick of dealing with all the printing and PDF issues with flutter.

I used to think that  https://github.com/DavBfr/dart_pdf is better but i found that its WAY too much work..

**Comment by premy** [comment]
@Afur I use your package to create a pdf from html, and it works just fine, cause I can see it displayed with the aid of flutter_full_pdf_viewer. Now I would like to be able to simply grab generatedPdfFilePath and send it to the native printer app. Could you pls point me into the right direction?

**Comment by Afur** [comment]
@premy I believe that you can use this plugin [https://pub.dev/packages/printing](https://pub.dev/packages/printing) since you have direct path to PDF document. However I've never had to use printing functionality inside flutter apps so I'm not 100% sure whether that plugin will be enough or not.
