### ISSUE TITLE
The corresponding parameter in the supertype 'Callback' is named 'path'

### ISSUE THREAD

**Issue by kw2019ltd** [Afur/flutter_html_to_pdf#7]
C:\Tools\flutter_windows_v1.0.0-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_html_to_pdf-0.4.0\android\src\main\kotlin\com\afur\flutterhtmltopdf\HtmlToPdfConverter.kt: (49, 44): The corresponding parameter in the supertype 'Callback' is named 'path'. This may cause problems when calling this function with named arguments.

> Task :flutter_html_to_pdf:prepareLintJar UP-TO-DATE
> Task :flutter_html_to_pdf:generateDebugSources UP-TO-DATE
> Task :flutter_html_to_pdf:javaPreCompileDebug
> Task :flutter_html_to_pdf:compileDebugJavaWithJavac
> Task :flutter_html_to_pdf:bundleLibCompileDebug
> Task :fluttertoast:generateDebugBuildConfig UP-TO-DATE
> Task :fluttertoast:prepareLintJar UP-TO-DATE
> Task :fluttertoast:generateDebugSources UP-TO-DATE
> Task :fluttertoast:javaPreCompileDebug

> Task :fluttertoast:compileDebugJavaWithJavac

**Comment by Afur** [comment]
@kw2019ltd Fixed with version **0.4.1**. Thanks
