### ISSUE TITLE
add option to pass url instead of html data

### ISSUE THREAD

**Issue by karnadii** [Afur/flutter_html_to_pdf#8]
request feature for passing url instead of html

**Comment by karnadii** [comment]
i made a commit to fix this issue #8 https://github.com/karnadii/flutter_html_to_pdf/commit/43ca79e0a701e4bd10464140e04187b3c4f1c680

I know almost nothing about kotlin, so I just copy and paste and make some small changes, If you are ok with my code, I can make a pr

**Comment by Afur** [comment]
Hi @karnadii thanks for sharing your idea. The code is acceptable but naturally it will require some extra testing before merge to make sure that this feature will be working in multiple situations without new bugs. 

The main problem is that your code contains only implementation for Android side and We also need to provide iOS implementation to make it work for both platforms. I'm not iOS developer so I'll need to check the how possible implementation will looks like in Swift 😄 Also there needs to be validation for "no internet" situation.

**Comment by karnadii** [comment]
oh right, I forgot about iOS, I never use it. I try to get the html using dio and then pass the html response to this plugin, but some website with javascript won't show nicely. Using my quick fix only can print some website (google). I hope you keep this issue open until you/someone can implement this feature, thanks.

**Comment by Afur** [comment]
@karnadii I'm working on iOS implementation. It's working so I should finish it during this weekend. 

But as far as this plugin is using the default system mechanism for printing web pages 
many of them will not look as many people expect. The final document will look like preview in printer dialog provided by system. I'll write this in README.

**Comment by Afur** [comment]
@karnadii You can submit PR with your Android changes

**Comment by karnadii** [comment]
@Afur done.
